#pragma config(Sensor, port4,  Gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port8,  LED,            sensorVexIQ_LED)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor5,          armMotor,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor7,         	clawMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         tailMotor,     tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define RATE 1.01
#define WAIT_CYCLE 20
#define MIN_SPEED 30
#define COUNT_PER_ROUND 960
#define GEAR_RATIO 1.5
#define DECEL_RATE 0.75
#define WHEEL_TRAVEL 20.0

#define ON_SPOT_TURN 0
#define LEFT_WHEEL_TURN 1
#define RIGHT_WHEEL_TURN 2
#define TWO_WHEEL_TURN 3

#define TASK_CLAW_CLOSE 0
#define TASK_CLAW_OPEN 1
#define TASK_TAIL_UP 2
#define TASK_TAIL_DOWN 3
#define TASK_RETURN_ARM 4

#define CLAW_OPEN -120
#define CLAW_CLOSE -450
#define CLAW_DELTA 65

#define TAIL_UP 2300
#define TAIL_DOWN 1250
#define TAIL_DELTA 65

#define ARM_DELTA 65
#define MS_PER_ENCODER_UNIT 1
#define MS_PER_DEGREE_ROBOT_TURN 12

#define GYRO_SAMPLEING_SECONDS 10
#define ACCEPTABLE_DRIFT_RANGE 0.08

float fGyroDriftRate;
int currentCount, pickUpTrigger, targetHeading, cubeLevel;
int iArmLv[4] = {80, 330, 900, 1300};

int taskAction;
float timeStamp;

void setGyroStable()
{
	fGyroDriftRate = 100;

	while (fGyroDriftRate > ACCEPTABLE_DRIFT_RANGE)
	{
		setTouchLEDColor(LED,colorRed);
		setTouchLEDBlinkTime(LED, 14,6);
		wait(3);
		setTouchLEDBlinkTime(LED, 0,1);
		wait(2);

		setTouchLEDColor(LED,colorGreen);
		setTouchLEDBlinkTime(LED, 8, 12);

		resetGyro(Gyro);
		clearTimer(T4);
		wait(GYRO_SAMPLEING_SECONDS);

		fGyroDriftRate = getGyroDegreesFloat(Gyro) / GYRO_SAMPLEING_SECONDS;

		if (fGyroDriftRate < ACCEPTABLE_DRIFT_RANGE)
			setTouchLEDColor(LED, colorGreen);
		else
			setTouchLEDColor(LED, colorRed);

		setTouchLEDBlinkTime(LED, 4, 4);
		wait(1);
		setTouchLEDColor(LED,colorNone);
		setTouchLEDBlinkTime(LED, 1, 0);
	}

}

float getGyroStable()
{
	return getGyroDegreesFloat(Gyro) - fGyroDriftRate * time1[T4] / 1000;
}

void resetGyroStable()
{
	resetGyro(Gyro);
	clearTimer(T4);
}

float cmToEncoderUnit(float distance)
{
	return distance * COUNT_PER_ROUND / WHEEL_TRAVEL / GEAR_RATIO / RATE;
}

void goStraightDecel(int distance, int maxSpeed, float Ki, float Kp, int slowZonePercent)
//For no load: Ki = 0.0026, Kp = 0.5
{
	float motorSpeed;
	float error = 0, integral = 0, output;
	int targetCount = cmToEncoderUnit(distance);
	float slowZone = targetCount * slowZonePercent / 100;

	writeDebugStreamLine("targetCount = %d", targetCount);
	writeDebugStreamLine("slowZone = %d", slowZone);

	currentCount = 0;
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);

	clearTimer( T2 );

	while ( currentCount < targetCount && time1[T2] < ( targetCount * MS_PER_ENCODER_UNIT * 100 / MIN_SPEED ) )
	{
		error = getGyroStable() - targetHeading;
		integral = integral + error;
		output = error * Kp + integral * Ki;

    if ( currentCount < ( targetCount - slowZone ) )
		{
			motorSpeed = maxSpeed;
		}
		else
		{
			motorSpeed = sgn(maxSpeed) * MIN_SPEED + DECEL_RATE * ( maxSpeed - sgn(maxSpeed) * MIN_SPEED ) * ( targetCount - currentCount ) / slowZone;
		}

		setMotorSpeed(leftMotor, motorSpeed + output);
		setMotorSpeed(rightMotor, motorSpeed - output);

		currentCount = abs( getMotorEncoder(leftMotor) + getMotorEncoder(rightMotor) ) / 2;
//		writeDebugStreamLine("%d:  %f,  %f,  %f,  %f,  %f", time1[T1], error, integral, output, motorSpeed, currentCount);
//		writeDebugStreamLine("%d: error %d, integral %d, output %d, motorSpeed %d, currentCount %d", time1[T1], error, integral, output, motorSpeed, currentCount);
//		displayCenteredBigTextLine(3, "%d, %d", currentCount, targetCount);
		displayCenteredBigTextLine(3, "%d, %d", getGyroStable(), targetHeading);
		wait1Msec(WAIT_CYCLE);
	}
		setMotorSpeed(leftMotor, 0);
		setMotorSpeed(rightMotor, 0);
}

void tailAction(int tailTarget)
{
	setMotorTarget( tailMotor, tailTarget, 100 );
	wait1Msec( abs( TAIL_UP - TAIL_DOWN ) * MS_PER_ENCODER_UNIT );
	setMotorSpeed( tailMotor, 0 );
}

void clawAction(int clawTarget)
{
	setMotorTarget( clawMotor, clawTarget, 100 );
	wait1Msec( abs( CLAW_CLOSE - CLAW_OPEN ) * MS_PER_ENCODER_UNIT );
	setMotorSpeed( clawMotor, 0 );
}

void returnArm()
{
	setMotorTarget(armMotor,iArmLv[0],100);
	wait1Msec( abs( getMotorEncoder(armMotor) - iArmLv[0] ) * MS_PER_ENCODER_UNIT );
	setMotorSpeed(armMotor, 0);
}

task simple_action()
{
	switch(taskAction)
	{
		case TASK_CLAW_CLOSE:
			clawAction(CLAW_CLOSE);
			break;
		case TASK_CLAW_OPEN:
			clawAction(CLAW_OPEN);
			break;
		case TASK_TAIL_UP:
			tailAction(TAIL_UP);
			break;
		case TASK_TAIL_DOWN:
			tailAction(TAIL_DOWN);
			break;
		case TASK_RETURN_ARM:
			returnArm();
			break;
	}
	EndTimeSlice();
}

void drop()
{
	clawAction( CLAW_OPEN );
	if ( getMotorEncoder(armMotor) > ( iArmLv[2] - ARM_DELTA ) )
	{
		// This block should had been done by goStraightDecel function instead.
		setMotorSpeed(leftMotor,-100);
		setMotorSpeed(rightMotor,-100);
		wait1Msec(100);
		setMotorSpeed(leftMotor,0);
		setMotorSpeed(rightMotor,0);
	}
	taskAction = TASK_RETURN_ARM;
	startTask(simple_action);
}

task task_drop()
{
	drop();
	EndTimeSlice();
}

task pick_up_cube()
{
	writeDebugStreamLine( "%f: %f, %f", time1[T1], currentCount, cmToEncoderUnit( pickUpTrigger ) );
	currentCount = 0;
	while ( currentCount < cmToEncoderUnit( pickUpTrigger ) )
		{
			writeDebugStreamLine( "%f: %f, %f", time1[T1], currentCount, cmToEncoderUnit( pickUpTrigger ) );
			wait1Msec( WAIT_CYCLE );
	}

	clawAction( CLAW_CLOSE );
	setMotorTarget( armMotor, iArmLv[cubeLevel], 100 );
	wait1Msec( abs( iArmLv[cubeLevel] - getMotorEncoder( armMotor ) ) * MS_PER_ENCODER_UNIT );
	setMotorSpeed( armMotor, 0 );
	EndTimeSlice();
}

void turnDecel( int inputHeading, int turnStyle, float Ki, float Kp, int baseSpeed, int delta )
{
	float error = 0, integral = 0, output;
	int degreeTurning = abs( getGyroStable() - inputHeading );

	targetHeading = inputHeading;
	clearTimer( T3 );

	while ( abs( getGyroStable() - targetHeading ) > delta && time1[T3] < ( degreeTurning * MS_PER_DEGREE_ROBOT_TURN * 100 / MIN_SPEED ) )
	{
		error = getGyroStable() - targetHeading;
		integral = integral + error;
		output = error * Kp + integral * Ki;

		switch ( turnStyle )
		{
			case ON_SPOT_TURN:
				setMotorSpeed(leftMotor, sgn(error) * baseSpeed + output);
				setMotorSpeed(rightMotor, -sgn(error) * baseSpeed - output);
				break;
			case LEFT_WHEEL_TURN:
				setMotorSpeed(leftMotor, sgn(error) * baseSpeed + output);
				setMotorSpeed(rightMotor, 0);
				break;
			case RIGHT_WHEEL_TURN:
				setMotorSpeed(leftMotor, 0);
				setMotorSpeed(rightMotor, -sgn(error) * baseSpeed - output);
				break;
			case TWO_WHEEL_TURN:
				setMotorSpeed(leftMotor, baseSpeed + output);
				setMotorSpeed(rightMotor, baseSpeed - output);
				break;
		}

		//writeDebugStreamLine("%d:  %d,  %d,  %d", time1[T1], error, integral, output);
		wait1Msec(WAIT_CYCLE);
	}
		setMotorSpeed(leftMotor, 0);
		setMotorSpeed(rightMotor, 0);
}

void greenCubeLow()
{
	goStraightDecel(17, 90, 0.0026, 0.5, 20);

	pickUpTrigger = 5; cubeLevel = 2;
	startTask( pick_up_cube );
	goStraightDecel(22, 30, 0.0026, 0.5, 0);

	goStraightDecel(30, 60, 0.003, 0.6, 30);

	drop();

}

void greenCubeLowHigh1()
{
	goStraightDecel(17, 90, 0.0026, 0.5, 20);

	pickUpTrigger = 5; cubeLevel = 2;
	startTask( pick_up_cube );
	goStraightDecel(22, 30, 0.0026, 0.5, 0);

	goStraightDecel(30, 60, 0.003, 0.6, 30);

	clawAction( CLAW_OPEN );

	taskAction = TASK_RETURN_ARM;
	startTask(simple_action);
	goStraightDecel(9, -90, 0.003, 0.6, 30);

	turnDecel( 90, ON_SPOT_TURN, 0, 0.3, 5,  2);
	clawAction(CLAW_CLOSE);
	taskAction = TASK_CLAW_OPEN;
	startTask(simple_action);

	goStraightDecel(11, 100, 0.0026, 0.5, 20);

	goStraightDecel(20, 60, 0.0026, 0.5, 60);

	pickUpTrigger = 4; cubeLevel = 3;
	startTask(pick_up_cube);
	goStraightDecel(20, 30, 0.003, 0.5, 30);
	wait1Msec(300);

	turnDecel(170, ON_SPOT_TURN, 0, 0.3, 5, 3);
	displayCenteredBigTextLine( 3, "%d, %d", getGyroStable(), targetHeading );
	wait1Msec(300);

	goStraightDecel(20, 90, 0.003, 0.5, 40);
	goStraightDecel(7, 30, 0.003, 0.5, 0);
	drop();

	taskAction = TASK_RETURN_ARM;
	startTask(simple_action);
	goStraightDecel(5, -100, 0.0026, 0.5, 0);
}

void LEDBusiness(int colour, int blinkTimeOn, int blinkTimeOff, int blinkColour, int blink)
{

	timeStamp = time1[T1];
	displayCenteredBigTextLine( 3, "%f", timeStamp );

	if (blink == 0)
	{
		setTouchLEDColor(LED, colour);
		waitUntil( getTouchLEDValue(LED) == 1 );
	}
	else if (blink ==1)
	{
		setTouchLEDColor(LED,colour);
		waitUntil(getTouchLEDValue(LED) == 1);
		setTouchLEDColor(LED,blinkColour);
		setTouchLEDBlinkTime(LED, blinkTimeOn, blinkTimeOff);
	}

	wait(0.3);
	resetGyroStable();
	targetHeading = 0;
}

void top_right_to_bottom_left()
{
	goStraightDecel(50, 100, 0.0026, 0.5, 20);
	turnDecel(-40, ON_SPOT_TURN, 0, 0.6, 5, 2);

	pickUpTrigger = 20; cubeLevel = 1;
	startTask( pick_up_cube );
	goStraightDecel(23, 90, 0.0026, 0.5, 30);

	turnDecel(-240, ON_SPOT_TURN, 0, 0.3, 5, 2);
	goStraightDecel(145, 100, 0.0028, 0.6, 0 );

	startTask(task_drop);

	setMotorSpeed(leftMotor, 100);
	setMotorSpeed(rightMotor, 100);
	wait1Msec(400);
	goStraightDecel(20, -100, 0.0028, 0.6, 0 );
}

void two_left_to_top_right()
{
	goStraightDecel(50, 100, 0.0026, 0.5, 20);
	turnDecel(40, ON_SPOT_TURN, 0, 0.6, 5, 2);

	pickUpTrigger = 20; cubeLevel = 1;
	startTask( pick_up_cube );
	goStraightDecel(23, 90, 0.0026, 0.5, 40);

	goStraightDecel(30, -90, 0.0026, 0.5, 20);

	turnDecel(-70, ON_SPOT_TURN, 0, 0.3, 8, 2);
	goStraightDecel(55, -100, 0.0028, 0.6, 0);

	taskAction = TASK_TAIL_UP;
	startTask(simple_action);

	targetHeading = -75;
	goStraightDecel(30, 100, 0.0028, 0.6, 20);
	turnDecel(-75, ON_SPOT_TURN, 0, 0.3, 10, 2);

	goStraightDecel(160, 100, 0.0028, 0.6, 0);
	turnDecel(-65, ON_SPOT_TURN, 0, 0.5, 30, 2);

	setMotorSpeed(leftMotor, 100);
	setMotorSpeed(rightMotor, 100);
	wait1Msec(500);

	startTask(task_drop);

	goStraightDecel(10, -100, 0.0028, 0.6, 0);

	turnDecel(30, LEFT_WHEEL_TURN, 0, 0.5, 30, 2);
	goStraightDecel(40, -100, 0.0028, 0.6, 0);

	turnDecel(5, RIGHT_WHEEL_TURN, 0, 0.5, 30, 2);

	taskAction = TASK_TAIL_DOWN;
	startTask(simple_action);

	setMotorSpeed(leftMotor, -100);
	setMotorSpeed(rightMotor, -100);
	wait1Msec(500);

	goStraightDecel(15, 100, 0.0026, 0.5, 0);

	}


void last_bonus()
{
	setMotorSpeed(leftMotor, 100);
	setMotorSpeed(rightMotor, 100);
	wait1Msec(150);

	setMotorSpeed(leftMotor, -100);
	wait1Msec(350);

	goStraightDecel(17, -100, 0.0025, 0.5, 0);

	taskAction = TASK_TAIL_UP;
	startTask(simple_action);
	turnDecel(70, ON_SPOT_TURN, 0, 0.3, 10, 2);

	goStraightDecel(150, 100, 0.0028, 0.6, 0);

	turnDecel(-145, ON_SPOT_TURN, 0, 0.3, 20, 5);
	goStraightDecel(20, -100, 0.0028, 0.6, 0);

	taskAction = TASK_TAIL_DOWN;
	startTask(simple_action);

	setMotorSpeed(leftMotor, -100);
	setMotorSpeed(rightMotor, -100);
	wait1Msec(500);

	goStraightDecel(10, 100, 0.0028, 0.6, 0);
}

void square()
{
	int i;

	goStraightDecel(40, 100, 0.0028, 0.3, 30);
	for (i=1;i<=4;i++)
	{
		goStraightDecel(40, 60, 0.0028, 0.3, 30);
		turnDecel(90*i, ON_SPOT_TURN, 0, 0.3, 5, 2);
		while (getTouchLEDValue(LED) == 0)
		{
			displayCenteredBigTextLine( 3, "%d, %d", getGyroStable(), getGyroDegrees(Gyro) );
		}
	}
}


task main()
{
	setMotorEncoderUnits( encoderCounts );

	// Define 0 point for claw, tail, and arm.
	setMotorSpeed( clawMotor, 100 );
	setMotorSpeed( tailMotor, -100 );
	setMotorSpeed( armMotor, -100 );
	wait(2);
	resetMotorEncoder( clawMotor );
	resetMotorEncoder( tailMotor );
	resetMotorEncoder( armMotor );

	// Get claw, tail, and arm ready for the game
	setMotorTarget( clawMotor, CLAW_OPEN, 100 );
	setMotorTarget( tailMotor, TAIL_DOWN, 100 );
	setMotorTarget( armMotor, iArmLv[0], 100 );
	wait( 0.7 );

	setTouchLEDColor(LED,colorOrange);
	waitUntil(getTouchLEDValue(LED) == 1);

	// Collect gyro drifting rate, and reset gyro
	setGyroStable();
	targetHeading = 0;

	// Get drive train ready for the game
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	setMotorBrakeMode(leftMotor, motorHold);
	setMotorBrakeMode(rightMotor, motorHold);

	// On the mark
	LEDBusiness( colorGreen, 0, 0, 0, 0 );
	clearTimer( T1 );
	//square();
	greenCubeLow();

	setMotorSpeed(leftMotor, -100);
	setMotorSpeed(rightMotor, -100);
	wait(1.3);
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);

	LEDBusiness( colorGreen, 0, 0, 0, 0 );
	greenCubeLowHigh1();

	LEDBusiness( colorGreen, 0, 0, 0, 0 );
	top_right_to_bottom_left();

	LEDBusiness( colorGreen, 0, 0, 0, 0 );
	two_left_to_top_right();

	LEDBusiness( colorGreen, 0, 0, 0, 0 );
	last_bonus();

	LEDBusiness( colorGreen, 0, 0, 0, 0 );

}
