#pragma config(Sensor, port8,  led,            sensorVexIQ_LED)
#pragma config(Motor,  motor1,          right,         tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          left,          tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          claw,          tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         tail,          tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         armmmm,        tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// First cube line up at first black line
task main()
{

setMotorBrakeMode(motor12, motorHold);
  setMotorSpeed(motor12, 0);  //The motor will now Hold  (resist movement and stay at position)
  sleep(1000);


 setTouchLEDColor(led,colorGreen);
 //Start autonomous by touching LED
 waitUntil(getTouchLEDValue(led) == 1);
  //Colour LEDs
 setTouchLEDColor(led,colorRed);
 setTouchLEDBlinkTime(led, 10, 20);
 // Drivemotor6
 setMotorTarget(motor6, 200, 100);
 setMotorTarget(motor1,-200, 100);
	wait1Msec(400);

 // Grab
 setMotorTarget(motor7,-100, 100);
 wait1Msec(200);

 // arm up

 setMotorTarget(armmmm,-400,100);
 wait1Msec(700);

  // Drive
 setMotorTarget(motor6,680, 100);
 setMotorTarget(motor1,-680, 100);
 wait1Msec(500);

  // arm down

 setMotorTarget(armmmm,-310,100);
 wait1Msec(200);

  // Grab
 setMotorTarget(motor7,0, 100);
 wait1Msec(300);

   // Drive
 setMotorTarget(motor6,-300, 100);
 setMotorTarget(motor1,300, 100);
 wait1Msec(500);

   // arm down

 setMotorTarget(armmmm,20,100);
 wait1Msec(200);
 //
setTouchLEDColor(led,colorBlue);/////////////////////////////////////////////////////////
waitUntil(getTouchLEDValue(led) == 1);

resetMotorEncoder(motor1);
resetMotorEncoder(motor6);
////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Drive
 setMotorTarget(motor6,200, 100);
 setMotorTarget(motor1,-200, 100);
 wait1Msec(400);

 // Grab
 setMotorTarget(motor7,-100, 100);
 wait1Msec(200);

 // arm up

 setMotorTarget(armmmm,-400,100);
 wait1Msec(700);

  // Drive
 setMotorTarget(motor6,680, 100);
 setMotorTarget(motor1,-680, 100);
 wait1Msec(500);

  // arm down

 setMotorTarget(armmmm,-310,100);
 wait1Msec(200);

  // release
 setMotorTarget(motor7,0, 100);
 wait1Msec(1000);

//////////////////////////////////////////////////DONE 1

   // Drive BACK
 setMotorTarget(motor6,-200, 100);
 setMotorTarget(motor1,200, 100);
 wait1Msec(300);




 // arm down

 setMotorTarget(armmmm,20,100);
 wait1Msec(1000);


 setTouchLEDColor(led,colorYellow); ///////////////////////////////////////////////////////////
waitUntil(getTouchLEDValue(led) == 1);

    // Drive fwd
 setMotorTarget(motor6,450, 100);
 setMotorTarget(motor1,-450, 100);
 wait1Msec(1000);

    // Drive turn
 setMotorTarget(motor6,55, 100);
 wait1Msec(1000);

  resetMotorEncoder(motor1);
 resetMotorEncoder(motor6);

 // Drive fwd
 setMotorTarget(motor6,600, 100);
 setMotorTarget(motor1,-600, 100);
 wait1Msec(1000);


   // grab
 setMotorTarget(motor7,-100, 100);
 wait1Msec(1000);

   // arm high

 setMotorTarget(armmmm,-600,100);
 wait1Msec(1000);
    resetMotorEncoder(motor1);
 resetMotorEncoder(motor6);
    // Drive rev
 setMotorTarget(motor6,-100, 100);
 setMotorTarget(motor1,100, 100);
 wait1Msec(1000);

    resetMotorEncoder(motor1);
 resetMotorEncoder(motor6);
    // Drive turn
 setMotorTarget(motor1,-300, 100);
 wait1Msec(1000);

   resetMotorEncoder(motor1);
 resetMotorEncoder(motor6);
     // Drive fwd
 setMotorTarget(motor6,290, 100);
 setMotorTarget(motor1,-290, 100);
 wait1Msec(1000);

    // grab
 setMotorTarget(motor7,20, 100);
 wait1Msec(1000);

      // Drive rev
 setMotorTarget(motor6,-150, 100);
 setMotorTarget(motor1,150, 100);
 wait1Msec(1000);
}
