#pragma config(Sensor, port9,  LED,            sensorVexIQ_LED)
#pragma config(Sensor, port10, Gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  motor2,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor5,          liftMotorR,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          clawMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor8,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         liftMotorL,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         scoopMotor,    tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define CLAW_CLOSE 450
#define CLAW_OPEN 50
#define CLAW_DELTA 20
#define SCOOPER_DELTA 35
#define ARM_DELTA 25
#define MS_PER_ENCODER_UNIT 1
#define ENCODER_UNIT_PER_SCOOP_ROUND 1920
#define FLIP_UP 1250
#define FLIP_DOWN 900

#define LIFT_LEVELS 4
int iLiftLevel[LIFT_LEVELS] = {15 ,400, 1100, 1830}; //pickup_inside, pickup_outside/transport,low_inside,low_outside,,high_inside

int iScoopPos[4] = { -150, 250, 815, 1000 }; //pick_cube, keep_ball/release cube, ready_to_scoop_ball, score_ball

void LEDBusiness(int colour, int blinkTimeOn, int blinkTimeOff, int blinkColour, int blink)
{
 if ( blink == 0 )
	{
		setTouchLEDColor( LED, colour );
		waitUntil( getTouchLEDValue( LED ) == 1 );
	}
	else if ( blink ==1 )
	{
		setTouchLEDColor( LED, colour );
		waitUntil( getTouchLEDValue( LED ) == 1 );
		setTouchLEDColor( LED, blinkColour );
		setTouchLEDBlinkTime( LED, blinkTimeOn, blinkTimeOff );
	}


}

void checkBatt(float min){
	float nCurrBatt = nImmediateBatteryLevel*1000;
	if(nCurrBatt<=min){
		LEDBusiness(colorRed, 2, 2, colorRedViolet, 1);
	}
}
task main()
{



}
