#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor4,          intakeMotor,   tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         armMotor,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         gateMotor,     tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define GEAR_RATIO 1.6667f
#define ARM_SPEED 100
#define GATE_SPEED 60
#define INTAKE_SPEED 100


int iChA_filtered=0, iChC_filtered=0;


int iDriveMapping[101] = {
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
10,10,10,10,10,10,10,10,10,10,
10,10,10,10,10,10,10,10,10,10,
20,20,20,20,20,20,20,20,20,20,
30,30,30,30,30,30,30,30,30,30,
40,40,40,40,40,40,40,40,40,40,
50,50,50,50,50,50,50,50,50,50,
60,62,64,66,68,70,72,74,76,78,
84,88,92,96,100,100,100,100,100,100,100};


int iTurnMapping[101] = {
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
30,30,30,30,30,30,30,30,30,30,
30,30,30,30,30,31,32,33,34,36,
38,40,40,40,40,40,40,42,46,48,
50,50,50,50,50,50,50,52,54,56,
58,58,59,59,60,60,60,60,60,60,
60,60,60,60,60,60,60,60,60,60,
60,60,60,62,62,63,63,64,64,64,
65,65,66,66,66,66,66,66,66,66,66};


task main()
{
	repeat (forever)
	{

		iChA_filtered=iDriveMapping[abs(getJoystickValue(ChA))]*sgn(getJoystickValue(ChA));
		iChC_filtered=iTurnMapping[abs(getJoystickValue(ChC))]*sgn(getJoystickValue(ChC));
		//iChC_filtered=iDriveMapping[abs(getJoystickValue(ChC))]*sgn(getJoystickValue(ChC))/GEAR_RATIO

		setMotorSpeed(leftMotor,(iChA_filtered+iChC_filtered)/1);
		setMotorSpeed(rightMotor,(iChA_filtered-iChC_filtered)/1);

    if (getJoystickValue(BtnLUp)== 1)
		{
			setMotorSpeed(armMotor, -1*ARM_SPEED);
		}
		else if (getJoystickValue(BtnLDown)==1)
		{
			setMotorSpeed(armMotor, ARM_SPEED);
		}
		else
		{
			setMotorSpeed(armMotor, 0);
		}

    if (getJoystickValue(BtnEUp)== 1)
		{
			setMotorSpeed(gateMotor, -1*GATE_SPEED);
		}
		else if (getJoystickValue(BtnEDown)==1)
		{
			setMotorSpeed(gateMotor, GATE_SPEED);
		}
		else
		{
			setMotorSpeed(gateMotor, 0);
		}

    if (getJoystickValue(BtnRUp)== 1)
		{
			setMotorSpeed(intakeMotor, -1*INTAKE_SPEED);
		}
		else if (getJoystickValue(BtnRDown)==1)
		{
			setMotorSpeed(intakeMotor, INTAKE_SPEED);
		}
		else
		{
			setMotorSpeed(intakeMotor, 0);
		}


	}
}
