#pragma config(Sensor, port8,  ColorSensor,    sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port10, LED,            sensorVexIQ_LED)
#pragma config(Sensor, port12, gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,          BR,            tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          clawMotor,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor5,          BL,            tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          FL,            tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          FR,            tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         armMotor,      tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float desired_distance;
float dt = 25;
float allowed_time = 7.5;
float iChC_filtered = 0.0;
float iChB_filtered = 0.0;
float iChA_filtered = 0.0;
float progressToGoal = getMotorEncoder(BL) * 1.414;
float desired_heading = 0.0;

#define GYRO_SAMPLING_SECONDS 10000
#define ACCEPTABLE_DRIFT_RANGE 0.08
float fGyroDriftRate;

#define COUNT_PER_ROUND 960
#define WHEEL_TRAVEL 20.0
#define GEAR_RATIO 2
#define RATE 1

#define LIFT_LEVELS 3
int iArmLevel[LIFT_LEVELS] = {30, 455, 550};
int in_between_level = 355;

bool claw_to_close = false;
#define CLAW_OPEN 145

float cmToEncoderUnit(float distance)
{
	return distance * COUNT_PER_ROUND / WHEEL_TRAVEL / GEAR_RATIO / RATE;
}

void setGyroStable()
{
	fGyroDriftRate = 100;

	while (fGyroDriftRate > ACCEPTABLE_DRIFT_RANGE)
	{
		// Let the LDH flashing to remind people do not move the robot.
		setTouchLEDColor(LED,colorRed);
		setTouchLEDBlinkTime(LED, 14,6);
		wait1Msec(3);
		setTouchLEDBlinkTime(LED, 0,1);
		wait1Msec(2);

		setTouchLEDColor(LED,colorGreen);
		setTouchLEDBlinkTime(LED, 8, 12);

		resetGyro(gyro);
		clearTimer(T4);
		wait1Msec(GYRO_SAMPLING_SECONDS);

		fGyroDriftRate = getGyroDegreesFloat(gyro) / GYRO_SAMPLING_SECONDS;

		if (fGyroDriftRate < ACCEPTABLE_DRIFT_RANGE)
			setTouchLEDColor(LED, colorGreen);
		else
			setTouchLEDColor(LED, colorRed);

		setTouchLEDBlinkTime(LED, 4, 4);
		wait1Msec(1);
		setTouchLEDColor(LED,colorNone);
		setTouchLEDBlinkTime(LED, 1, 0);
	}

}

float getGyroStable()
{
	return getGyroDegreesFloat(gyro) - fGyroDriftRate * time1[T4] / 1000;
}

void resetGyroStable()
{
	resetGyro(gyro);
	clearTimer(T4);
}

typedef struct {
	float setpoint;
	float measured_value;
	float integral;
	float prev_error;
	float kp;
	float ki;
	float kd;
	float delta;
}structPID;

structPID pidStrafe;
structPID pidOrientation;
structPID pidLight;
structPID pidEncoder;

float PIDControl (structPID &pid)
{
	float error = pid.setpoint - pid.measured_value;

	if ( abs(error) < pid.delta )
		error = 0;

	pid.integral = pid.integral + error * dt;
	float derivative = ( error - pid.prev_error ) / dt;
	float output = pid.kp * error + pid.ki * pid.integral + pid.kd * derivative;
	pid.prev_error = error;

	return output;
}

void strafePID(float direction, int distance, int maxJoyStick, float Kp, float Ki, float Kd, int delta)
{
	int tmpJoyStick, motor_a, motor_b, selector_a, selector_b;
	float pre_FL = 0, pre_FR = 0, pre_BL = 0, pre_BR = 0;

	pidStrafe.setpoint = cmToEncoderUnit(distance) / sqrt(2);
	pidStrafe.measured_value = 0;
	pidStrafe.kp = Kp;
	pidStrafe.ki = Ki;
	pidStrafe.kd = Kd;
	pidStrafe.delta = cmToEncoderUnit(delta);

/*
	pidLight.setpoint = getColorGrayscale(ColorSensor);
	pidLight.measured_value = 0;
	pidLight.kp = 0.03;
	pidLight.ki = 0.000002;
	pidLight.kd = 0.001;
	pidLight.delta = 30;
*/

	pidEncoder.setpoint = 0;
	pidEncoder.measured_value = 0;
	pidEncoder.kp = 0.015;
	pidEncoder.ki = 0.000002;
	pidEncoder.kd = 0.005;
	pidEncoder.delta = 30;

	resetMotorEncoder(FL);
	resetMotorEncoder(FR);
	resetMotorEncoder(BL);
	resetMotorEncoder(BR);

	switch(direction)
	{
		case 1:
			if(distance > 0)
		  {
		  	motor_a = FL;
		  	motor_b = BL;
			}
			else
			{
			 	motor_a = FR;
		  	motor_b = BR;
			}
	  	selector_a = 0;
	  	selector_b = 1;
	  	break;

		case 2:
		  motor_a = FL;
		  motor_b = BR;
	  	selector_a = 1;
	  	selector_b = 1;
	  	break;

		case 3:
		  if(distance > 0)
		  {
		  	motor_a = BR;
		  	motor_b = BL;
			}
			else
			{
			 	motor_a = FR;
		  	motor_b = FL;
			}
	  	selector_a = 1;
	  	selector_b = 0;
	  	break;

	  case 4:
		  motor_a = FR;
		  motor_b = BL;
	  	selector_a = 1;
	  	selector_b = -1;
	  	break;
	}

	while ( abs(pidStrafe.setpoint - pidStrafe.measured_value) > pidStrafe.delta )
	{
		pidStrafe.measured_value = sgn(pidStrafe.setpoint) * (abs(getMotorEncoder(motor_a)) + abs(getMotorEncoder(motor_b))) / 2;

		tmpJoyStick = PIDControl(pidStrafe);
		if (abs(tmpJoyStick) > maxJoyStick)
			tmpJoyStick = maxJoyStick * sgn(tmpJoyStick);

		iChA_filtered = tmpJoyStick * selector_a;
		iChB_filtered = tmpJoyStick * selector_b;
/*
		pidLight.measured_value = getColorGrayscale(ColorSensor);
		iChA_filtered = -sgn(abs(getMotorEncoder(FL))+abs(getMotorEncoder(FR))-abs(getMotorEncoder(BL))-abs(getMotorEncoder(BR))) * PIDControl(pidLight);
		writeDebugStreamLine( "%f %f %f %f %f %f %f", getTimerValue(T2), iChA_filtered, iChB_filtered, abs(getMotorEncoder(FL))+abs(getMotorEncoder(FR)), abs(getMotorEncoder(BL))+abs(getMotorEncoder(BR)), pidLight.prev_error, pidLight.measured_value );
*/
		//pidEncoder.measured_value = abs(getMotorEncoder(BL))+abs(getMotorEncoder(BR))-abs(getMotorEncoder(FL))-abs(getMotorEncoder(FR));

		pidEncoder.measured_value = abs(getMotorEncoder(motor_b))-abs(getMotorEncoder(motor_a));
		switch (direction)
		{
			case 1:
				iChA_filtered = PIDControl(pidEncoder);
				break;
			case 3:
				iChB_filtered = PIDControl(pidEncoder);
				break;
		}

		writeDebugStreamLine( "%f %f %f %f %f %f", getTimerValue(T2), iChA_filtered, iChB_filtered, abs(getMotorEncoder(FL))+abs(getMotorEncoder(FR)), abs(getMotorEncoder(BL))+abs(getMotorEncoder(BR)), pidEncoder.measured_value );

		//writeDebugStreamLine( "%f %f %f %f %f %f %f %f", getTimerValue(T2), iChA_filtered, iChC_filtered, getGyroDegrees(gyro), getGyroStable(), desired_heading, pidStrafe.setpoint, pidStrafe.measured_value );
		//writeDebugStreamLine( "%f %f %f %f %f %f %f %f %f", getTimerValue(T2), iChA_filtered, abs(getMotorEncoder(FL))-pre_FL, abs(getMotorEncoder(FR))-pre_FR, abs(getMotorEncoder(BL))-pre_BL, abs(getMotorEncoder(BR))-pre_BR, abs(getMotorEncoder(FL))+abs(getMotorEncoder(FR)), abs(getMotorEncoder(BL))+abs(getMotorEncoder(BR)), pidLight.measured_value );

		wait1Msec(dt);
	}
	iChA_filtered = 0;
	iChB_filtered = 0;
}

task drive()
{
	while (true)
	{
		pidOrientation.measured_value = getGyroStable();
		pidOrientation.setpoint = desired_heading;

		iChC_filtered = -PIDControl(pidOrientation);
		//writeDebugStreamLine( "%f %f %f %f %f %f %f %f", getTimerValue(T2), iChA_filtered, iChC_filtered, getGyroDegrees(gyro), getGyroStable(), desired_heading );

		setMotorSpeed( FL, 0 + iChA_filtered + iChB_filtered - iChC_filtered );
		setMotorSpeed( BL, 0 + iChA_filtered - iChB_filtered - iChC_filtered );
		setMotorSpeed( FR, 0 - iChA_filtered + iChB_filtered - iChC_filtered );
		setMotorSpeed( BR, 0 - iChA_filtered - iChB_filtered - iChC_filtered );
		wait1Msec(dt);
	}
}

task claw_move()
{
	int claw_position, prev_claw = -1;

	setMotorBrakeMode(clawMotor, motorHold);

	while (true)
	{
		if (claw_to_close)
		{
			claw_position = getMotorEncoder(clawMotor);
			if (prev_claw == claw_position)
			{
				setMotorSpeed(clawMotor, 0);
				prev_claw = 0;
			}
			else
			{
				prev_claw = claw_position;
				setMotorSpeed(clawMotor, -100);
				wait1Msec(100);
			}
		}
		else
		{
			setMotorTarget(clawMotor, CLAW_OPEN, 100);
		}

		wait1Msec(dt);
	}
}


// remember these values for orientation: DriveStraightPID(20, 0.7, 0, 0, 5)
task main()
{
//	getColorGrayscale(ColorSensor);
//	while(true)
//		displaySensorValues(line3,ColorSensor);

	setGyroStable();
	resetGyroStable();

	setMotorBrakeMode(BL, motorHold);
	setMotorBrakeMode(FL, motorHold);
	setMotorBrakeMode(BR, motorHold);
	setMotorBrakeMode(FR, motorHold);
	resetTimer(T2);
	setMotorEncoderUnits(encoderCounts);

	clearDebugStream();

	pidOrientation.delta = 0.6;
	pidOrientation.kp = 1;
	pidOrientation.ki = 0.00001;
	pidOrientation.kd = 0.0001;

	startTask(drive);
	//startTask(claw_move);

	//setMotorTarget(armMotor, iArmLevel[1], 100);

	strafePID(1, -100, 60, 0.18, 0, 0, 1);
	wait1Msec(1000);
	strafePID(1, 100, 60, 0.18, 0, 0, 1);
	//desired_heading = 90;
	pidOrientation.delta = 1;
	waitUntil( abs(getGyroStable() - desired_heading) <= pidOrientation.delta );
	stopAllTasks();
}
