#pragma config(Motor,  motor1,          rightMotor,    tmotorVexIQ, PIDControl, driveRight, encoder)
#pragma config(Motor,  motor6,          leftMotor,     tmotorVexIQ, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motor10,         armMotor,      tmotorVexIQ, PIDControl, encoder)
/*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*/

task main()
{
	int targetCount, motorSpeed, currentCount;
	int MIN_SPEED = 10;
	int MAX_SPEED = 40;
	int COUNT_PER_RATOTE = 960;
	int GEAR_RATIO = 3;
	int SLOW_ZONE = 10*COUNT_PER_RATOTE/20.0/GEAR_RATIO; // 10cm
	writeDebugStreamLine("SLOW_ZONE = %d", SLOW_ZONE);
	int decelRatio = 1;


	targetCount = 100*COUNT_PER_RATOTE/20/GEAR_RATIO;
	writeDebugStreamLine("targetCount = %d", targetCount);

	setMotorEncoderUnits(encoderCounts);
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	setMotorBrakeMode(leftMotor, motorHold);
	setMotorBrakeMode(rightMotor, motorHold);

	currentCount = (getMotorEncoder(leftMotor)+getMotorEncoder(rightMotor))/2;
	while ( currentCount < targetCount )
	{
    	if ( currentCount < ( targetCount - SLOW_ZONE ) )
		{
			setMotorSpeed(leftMotor, MAX_SPEED);
			setMotorSpeed(rightMotor, MAX_SPEED);
			datalogDataGroupStart();
			datalogAddValue(0, MAX_SPEED);
			datalogAddValue(1, MAX_SPEED);
			datalogDataGroupEnd();
		}
		else
		{
			motorSpeed = MIN_SPEED + decelRatio * ( MAX_SPEED - MIN_SPEED ) * ( targetCount - currentCount ) / SLOW_ZONE;
			setMotorSpeed(leftMotor, motorSpeed);
			setMotorSpeed(rightMotor, motorSpeed);
			datalogDataGroupStart();
			datalogAddValue(0, motorSpeed);
			datalogAddValue(1, motorSpeed);
			datalogDataGroupEnd();
		}

		currentCount = (getMotorEncoder(leftMotor)+getMotorEncoder(rightMotor))/2;
	}
		setMotorSpeed(leftMotor, 0);
		setMotorSpeed(rightMotor, 0);
}
