#pragma config(Sensor, port4,  Gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,          rightMotor,    tmotorVexIQ, PIDControl, driveRight, encoder)
#pragma config(Motor,  motor6,          leftMotor,     tmotorVexIQ, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motor10,         armMotor,      tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*/

task main()
{
	int minSpeed = 5;
	int maxSpeed = 35;
	int countPerRotate = 960;
	int gearRatio = 3;
	float decelRatio = 0.75;
	int slowZone = 10*countPerRotate/20.0/gearRatio; // 10cm
	int targetCount, motorSpeed, currentCount;
	float error,Kp=0.5;

	targetCount = 100*countPerRotate/20/gearRatio;

	writeDebugStreamLine("targetCount = %d", targetCount);
	writeDebugStreamLine("slowZone = %d", slowZone);

	wait(1);
	resetGyro(Gyro);
	setMotorEncoderUnits(encoderCounts);
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	setMotorBrakeMode(leftMotor, motorHold);
	setMotorBrakeMode(rightMotor, motorHold);

	currentCount = 0;
	while ( currentCount < targetCount )
	{
		error = ( getGyroDegreesFloat(Gyro) - 0 ) * Kp;
    if ( currentCount < ( targetCount - slowZone ) )
		{
			setMotorSpeed(leftMotor, maxSpeed + error);
			setMotorSpeed(rightMotor, maxSpeed - error);

			datalogDataGroupStart();
			datalogAddValue(0, maxSpeed);
			datalogAddValue(1, maxSpeed);
			datalogDataGroupEnd();
		}
		else
		{
			motorSpeed = minSpeed + decelRatio * ( maxSpeed - minSpeed ) * ( targetCount - currentCount ) / slowZone;
			setMotorSpeed(leftMotor, motorSpeed + error);
			setMotorSpeed(rightMotor, motorSpeed - error);

			datalogDataGroupStart();
			datalogAddValue(0, motorSpeed);
			datalogAddValue(1, motorSpeed);
			datalogDataGroupEnd();
		}

		currentCount = ( getMotorEncoder(leftMotor) + getMotorEncoder(rightMotor) ) / 2;
		wait1Msec(20);
	}
		setMotorSpeed(leftMotor, 0);
		setMotorSpeed(rightMotor, 0);
}
