#pragma config(Motor,  motor1,          rightMotor,    tmotorVexIQ, PIDControl, driveRight, encoder)
#pragma config(Motor,  motor6,          leftMotor,     tmotorVexIQ, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motor10,         armMotor,      tmotorVexIQ, PIDControl, encoder)
/*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*/

task main()
{
	float TargetDegree;
	int motorSpeed = 10;

	TargetDegree = 100/20/3*360;

	resetMotorEncoder(leftMotor);
	setMotorBrakeMode(leftMotor, motorHold);
	setMotorBrakeMode(rightMotor, motorHold);

	while ( getMotorEncoder(leftMotor) < TargetDegree )
	{
    if ( getMotorEncoder(leftMotor) < TargetDegree*0.6 )
		{
			setMotorSpeed(leftMotor, 60);
			setMotorSpeed(rightMotor, 60);
		}
		else
		{
			setMotorSpeed(leftMotor, motorSpeed);
			setMotorSpeed(rightMotor, motorSpeed);
		}
	}
		setMotorSpeed(leftMotor, 0);
		setMotorSpeed(rightMotor, 0);
}
