#pragma config(Motor,  motor6,          leftMotor,     tmotorVexIQ, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motor1,         rightMotor,    tmotorVexIQ, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int iChA_filtered=0, iChC_filtered=0;
int iDeadZone = 10, iMaxZone = 95;

task main()
{
	repeat (forever)
	{
		if ( abs(getJoystickValue(ChA)) < iDeadZone)
		{
			iChA_filtered = 0;
		}
		else
		{
			iChA_filtered = getJoystickValue(ChA);
		}

		if ( abs(getJoystickValue(ChC)) < iDeadZone)
		{
			iChC_filtered = 0;
		}
		else if ( abs(getJoystickValue(ChC)) < iMaxZone)
		{
			iChC_filtered = getJoystickValue(ChA)/3*sgn(getJoystickValue(ChC));
		}
		else
		{
			iChC_filtered = 100*sgn(getJoystickValue(ChC));
		}

		setMotorSpeed(leftMotor,(iChA_filtered+iChC_filtered)/2);
		setMotorSpeed(rightMotor,(iChA_filtered-iChC_filtered)/2);
	}
}
