#pragma config(Motor,  motor6,          leftMotor,     tmotorVexIQ, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motor1,         rightMotor,    tmotorVexIQ, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int iChA_filtered=0, iChC_filtered=0;
int iGearRatio = 3;

int iDriveMapping[101] = {
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
10,10,10,10,10,10,10,10,10,10,
10,10,10,10,10,10,10,10,10,10,
20,20,20,20,20,20,20,20,20,20,
30,30,30,30,30,30,30,30,30,30,
40,40,40,40,40,40,40,40,40,40,
50,50,50,50,50,50,50,50,50,50,
60,62,64,66,68,70,72,74,76,78,
84,88,92,96,100,100,100,100,100,100,100};


int iTurnMapping[101] = {
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
20,20,20,20,20,20,20,20,20,20,
20,20,20,20,20,20,21,21,22,22,
23,23,24,24,25,26,27,28,29,30,
31,32,33,34,35,35,36,36,37,37,
38,38,39,39,40,40,40,40,40,40,
40,40,40,40,40,40,40,40,40,40,
40,40,41,41,42,42,43,43,44,44,
45,45,45,45,45,45,45,45,45,45,45};


task main()
{
	repeat (forever)
	{

		iChA_filtered=iDriveMapping[abs(getJoystickValue(ChA))]*sgn(getJoystickValue(ChA));
		iChC_filtered=iTurnMapping[abs(getJoystickValue(ChC))]*sgn(getJoystickValue(ChC));
		//iChC_filtered=iDriveMapping[abs(getJoystickValue(ChC))]*sgn(getJoystickValue(ChC))/iGearRatiiGearRatio

		setMotorSpeed(leftMotor,(iChA_filtered+iChC_filtered)/2);
		setMotorSpeed(rightMotor,(iChA_filtered-iChC_filtered)/2);

	}
}
