#pragma config(Motor,  motor10,          FrontArm,      tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          LeftMotor,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor1,         RightMotor,    tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	repeat (forever) {
		int power=getJoystickValue(ChA);
		int turn=getJoystickValue(ChB);
		int arm=getJoystickValue(ChD);

		if (abs(power) > 30 || abs(turn) > 30) {
			setMotorSpeed(LeftMotor, (power + turn) / 2);
			setMotorSpeed(RightMotor, (power - turn) / 2);
		}
		else {
			setMotorBrakeMode(LeftMotor,motorBrake);
			setMotorBrakeMode(RightMotor,motorBrake);
			setMotorSpeed(LeftMotor,0);
			setMotorSpeed(RightMotor,0);
		}

		if (abs(getJoystickValue(ChD)) > 10) {
			setMotorSpeed(FrontArm, arm / 1.5);
		}
		else {
			setMotorBrakeMode(FrontArm,motorHold);
			setMotorSpeed(FrontArm,0);
		}
	}
}
