#pragma config(Sensor, port4,  Gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port8,  LED,            sensorVexIQ_LED)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor7,          clawMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         tailMotor,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor12,         armMotor,      tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#define WAIT_CYCLE 20
#define MIN_SPEED 20
#define COUNT_PER_ROUND 960
#define GEAR_RATIO 1.5
#define DECEL_RATE 0.75
#define SLOW_ZONE_PERCENT 40
#define WHEEL_TRAVEL 20.0


#define ARM_SPEED 100
#define TAIL_SPEED 60
#define CLAW_SPEED 100

#define CLAW_OPEN -120
#define CLAW_CLOSE -450
#define CLAW_DELTA 65

#define TAIL_UP 2000
#define TAIL_DOWN 960
#define TAIL_DELTA 65

#define ARM_DELTA 65
#define MS_PER_ENCODER_UNIT 1


int currentCount;
int iArmLv[4] = {105, 400, 1050, 1455};

int tailTarget;
bool tailMoving = false, armMoving = false;

void Initialize()
// Prepare robot
{
	wait(1);
	clearTimer(T1);
	resetGyro(Gyro);

	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	setMotorBrakeMode(leftMotor, motorHold);
	setMotorBrakeMode(rightMotor, motorHold);

}

float cmToEncoderUnit(float distance)
{
	return distance * COUNT_PER_ROUND / WHEEL_TRAVEL / GEAR_RATIO;
}

void goStraightDecel(int maxSpeed, float Ki, float Kp, int distance)
//For no load: Ki = 0.0026, Kp = 0.5
{
	float motorSpeed;
	float error = 0, integral = 0, output;
	int targetCount = cmToEncoderUnit(distance);
	float slowZone = targetCount * SLOW_ZONE_PERCENT / 100;

	writeDebugStreamLine("targetCount = %d", targetCount);
	writeDebugStreamLine("slowZone = %d", slowZone);

	//Initialize();

	while ( currentCount < targetCount )
	{
		error = getGyroDegreesFloat(Gyro) - 0;
		integral = integral + error;
		output = error * Kp + integral * Ki;

    if ( currentCount < ( targetCount - slowZone ) )
		{
			motorSpeed = maxSpeed;
		}
		else
		{
			motorSpeed = MIN_SPEED + DECEL_RATE * ( maxSpeed - MIN_SPEED ) * ( targetCount - currentCount ) / slowZone;
		}

		setMotorSpeed(leftMotor, motorSpeed + output);
		setMotorSpeed(rightMotor, motorSpeed - output);

		currentCount = ( getMotorEncoder(leftMotor) + getMotorEncoder(rightMotor) ) / 2;
//		writeDebugStreamLine("%d:  %f,  %f,  %f,  %f,  %f", time1[T1], error, integral, output, motorSpeed, currentCount);
//		writeDebugStreamLine("%d: error %d, integral %d, output %d, motorSpeed %d, currentCount %d", time1[T1], error, integral, output, motorSpeed, currentCount);
		wait1Msec(WAIT_CYCLE);
	}
		setMotorSpeed(leftMotor, 0);
		setMotorSpeed(rightMotor, 0);
}

void goStraightCoast(int maxSpeed, float Ki, float Kp, int distance)
//For no load: Ki = 0.0026, Kp = 0.5
{
	float motorSpeed;
	float error = 0, integral = 0, output;
	int targetCount = cmToEncoderUnit(distance);
	float slowZone = targetCount * SLOW_ZONE_PERCENT / 100;

	writeDebugStreamLine("targetCount = %d", targetCount);
	writeDebugStreamLine("slowZone = %d", slowZone);

	//Initialize();
	setMotorBrakeMode(leftMotor, motorCoast);
	setMotorBrakeMode(rightMotor, motorCoast);

	while ( currentCount < targetCount )
	{
		error = getGyroDegreesFloat(Gyro) - 0;
		integral = integral + error;
		output = error * Kp + integral * Ki;

		motorSpeed = maxSpeed;

		setMotorSpeed(leftMotor, motorSpeed + output);
		setMotorSpeed(rightMotor, motorSpeed - output);

		currentCount = ( getMotorEncoder(leftMotor) + getMotorEncoder(rightMotor) ) / 2;
//		writeDebugStreamLine("%d:  %f,  %f,  %f,  %f,  %f", time1[T1], error, integral, output, motorSpeed, currentCount);
//		writeDebugStreamLine("%d: error %d, integral %d, output %d, motorSpeed %d, currentCount %d", time1[T1], error, integral, output, motorSpeed, currentCount);
		wait1Msec(WAIT_CYCLE);
	}
		setMotorSpeed(leftMotor, 0);
		setMotorSpeed(rightMotor, 0);
}

void pickup()
{
	armMoving = true;
	setMotorTarget( clawMotor, CLAW_CLOSE, 100 );
	wait1Msec( abs( CLAW_CLOSE - CLAW_OPEN ) * MS_PER_ENCODER_UNIT );
	setMotorSpeed( clawMotor, 0 );
	setMotorTarget( armMotor, iArmLv[1], 100 );
	wait1Msec( abs( iArmLv[1] - getMotorEncoder( armMotor ) ) * MS_PER_ENCODER_UNIT );
	armMoving = false;
}

task pick_up_low_green()
{
	while ( currentCount < cmToEncoderUnit( 22 ) )
		writeDebugStreamLine( "%f: %f, %f", time1[T1], currentCount, cmToEncoderUnit( 22 ) );
		wait1Msec( WAIT_CYCLE );

	pickup();
	setMotorTarget( armMotor, iArmLv[2], 100 );
	wait1Msec( abs( iArmLv[2] - getMotorEncoder( armMotor ) ) * MS_PER_ENCODER_UNIT );
	setMotorSpeed( armMotor, 0 );

	EndTimeSlice();
}

task main()
{
	setMotorEncoderUnits(encoderCounts);

	setMotorSpeed(clawMotor, 100);
	setMotorSpeed(tailMotor, -100);
	setMotorSpeed(armMotor, -100);
	wait(2);
	resetMotorEncoder(clawMotor);
	resetMotorEncoder(tailMotor);
	resetMotorEncoder(armMotor);

	setMotorTarget(clawMotor, CLAW_OPEN, 100);
	setMotorTarget(tailMotor, TAIL_DOWN, 100);
	setMotorTarget(armMotor, iArmLv[0], 100);
	wait(0.7);

	Initialize();

	currentCount = 0;
//	startTask( pick_up_low_green );
	goStraightDecel(90, 0.0028, 0.5, 20);
	pickup();
	setMotorTarget( armMotor, iArmLv[2], 100 );
	wait1Msec( abs( iArmLv[2] - getMotorEncoder( armMotor ) ) * MS_PER_ENCODER_UNIT );
	setMotorSpeed( armMotor, 0 );
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	setMotorBrakeMode(leftMotor, motorHold);
	setMotorBrakeMode(rightMotor, motorHold);
	goStraightDecel(90, 0.002, 0.5, 48);
}
