#pragma config(Motor,  motor3,          rightMotorF,   tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor4,          flogMotorL,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotorB,   tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor9,          leftMotorF,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor10,         flogMotorR,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor12,         leftMotorB,    tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int rightSpeed, leftSpeed;

task main()
{
	setMotorBrakeMode( rightMotorB, motorHold );
	setMotorBrakeMode( rightMotorF, motorHold );
	setMotorBrakeMode( leftMotorB, motorHold );
	setMotorBrakeMode( leftMotorF, motorHold );

	while (true)
	{
		leftSpeed = getJoystickValue(ChA) - getJoystickValue(ChC);
		rightSpeed = getJoystickValue(ChA) + getJoystickValue(ChC);
		setMotorSpeed( rightMotorB, rightSpeed );
		setMotorSpeed( rightMotorF,  rightSpeed );
		setMotorSpeed( leftMotorB, leftSpeed );
		setMotorSpeed( leftMotorF, leftSpeed );

		if ( getJoystickValue(BtnLUp) == 1 )
		{
			setMotorSpeed(flogMotorL, 100);
			setMotorSpeed( flogMotorR, 100);
		}

		else if ( getJoystickValue(BtnLDown) == 1 )
		{
			setMotorSpeed(flogMotorL, -100);
			setMotorSpeed(flogMotorR, -100);
		}

		else
		{
			setMotorSpeed(flogMotorL, 0);
			setMotorSpeed(flogMotorR, 0);
		}
	}
}
