#pragma config(Sensor, port1,  LED,            sensorVexIQ_LED)
#pragma config(Motor,  motor2,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor5,          liftMotorR,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          clawMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor8,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         liftMotorL,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         scoopMotor,    tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define CLAW_CLOSE 450
#define CLAW_OPEN 50
#define CLAW_DELTA 20
#define SCOOPER_DELTA 35
#define LIFT_DELTA 25
#define MS_PER_ENCODER_UNIT 1
#define ENCODER_UNIT_PER_SCOOP_ROUND 1920
#define WAIT_CYCLE 20
#define COUNT_PER_ROUND 960
#define MS_PER_DEGREE_ROBOT_TURN 12

int pickUpTrigger, clawTarget, liftLevel;


#define LIFT_LEVELS 5
int iLiftLevel[LIFT_LEVELS] = {15 ,420, 1100, 1500, 1830}; //pickup_inside, pickup_outside/transport,low_inside,low_outside,,high_inside

int iScoopPos[4] = { -300, 280, 815, 1000 }; //pick_cube, keep_ball/release cube, ready_to_scoop_ball, score_ball

int turnNumber = 0;

void iCheckBattLevel(float min, float closemin){
	float nBattLevel = 0;
	float BattLevel = 0;
	for(int i = 0; i<1000; i++){
		BattLevel = BattLevel+(nImmediateBatteryLevel/1000);
		wait1Msec(10);
	}
	nBattLevel = BattLevel/1000;
	displayCenteredBigTextLine(3, "%f", nBattLevel);
	if(nBattLevel<min){
		setTouchLEDRGB(LED,255, 0, 0);
		waitUntil(getTouchLEDValue(LED)==1);
		setTouchLEDColor(LED, colorNone);
		}else if(nBattLevel<=closemin){
		setTouchLEDRGB(LED,255, 125, 125);
		waitUntil(getTouchLEDValue(LED)==1);
		setTouchLEDColor(LED, colorNone);
	}
}

void LEDBusiness(int colour, int blinkTimeOn, int blinkTimeOff, int blinkColour, int blink)
{

	timeStamp = time1[T1];
	displayCenteredBigTextLine( 3, "%f", timeStamp );

	if (blink == 0)
	{
		setTouchLEDColor(LED, colour);
		waitUntil( getTouchLEDValue(LED) == 1 );
	}
	else if (blink ==1)
	{
		setTouchLEDColor(LED,colour);
		waitUntil(getTouchLEDValue(LED) == 1);
		setTouchLEDColor(LED,blinkColour);
		setTouchLEDBlinkTime(LED, blinkTimeOn, blinkTimeOff);
	}

}

void clawAction(int targetName)
{
	setMotorTarget( clawMotor, targetName, 100 );
	wait1Msec( abs( CLAW_CLOSE - CLAW_OPEN ) * MS_PER_ENCODER_UNIT );
	setMotorSpeed( clawMotor, 0 );
}

void scoreBalls()
{
	setMotorSpeed(leftMotor,30);
	setMotorSpeed(rightMotor,30);

	setMotorTarget(scoopMotor,turnNumber*ENCODER_UNIT_PER_SCOOP_ROUND+iScoopPos[3],100);
	wait1Msec( abs( iScoopPos[3] - iScoopPos[1] ) * MS_PER_ENCODER_UNIT );
	wait1Msec(100);
	setMotorSpeed(leftMotor,0);
	setMotorSpeed(rightMotor,0);
	setMotorTarget(scoopMotor,turnNumber*ENCODER_UNIT_PER_SCOOP_ROUND+iScoopPos[2],100);
	wait1Msec( abs( iScoopPos[3] - iScoopPos[2] ) * MS_PER_ENCODER_UNIT );
}

task pick_up_cube()
{
	currentCount = 0;
    // We need to rewrite this into time wait.
	while ( currentCount < cmToEncoderUnit( pickUpTrigger ) )
	{
	
		wait1Msec( WAIT_CYCLE );
	}

	clawAction( clawTarget );
	setMotorTarget( liftMotorL, iLiftLevel[liftLevel], 100 );
	setMotorTarget( liftMotorR, iLiftLevel[liftLevel], 100 );
	wait1Msec(abs(getMotorEncoder(liftMotorL)-iLiftLevel[liftLevel])*MS_PER_ENCODER_UNIT);
	wait1Msec(300);
	EndTimeSlice();
}

void right_low_green_two_blue()
{
	GoStraight(5 cm, -60 as seped);

	pickUpTrigger = 4; liftLevel = 3; clawTarget = CLAW_CLOSE;
	startTask( pick_up_cube );

	GoStraight(10 cm, -30 as speed);
	setMotorTarget(liftMotorL, iLiftLevel[liftLevel],100);
	setMotorTarget(liftMotorR, iLiftLevel[liftLevel],100);

	GoStraight(55 cm, -40 as speed);

	clawAction(CLAW_OPEN);

	GoStraight(5 cm, 30 as speed);
	setMotorTarget(clawMotor, CLAW_CLOSE,30);
	setMotorTarget(liftMotorL, iLiftLevel[1],100);
	setMotorTarget(liftMotorR, iLiftLevel[1],100);
	Turn(110 degree, ON_SPOT_TURN);

	GoStraight(25 cm, 60 as speed);
	setMotorTarget(scoopMotor, iScoopPos[0], 100);
	GoStraight(10 cm, -40 as speed);

	Turn(185 degree, ON_SPOT_TURN);

	GoStraight(65 cm, -100 as speed);

	clawAction(CLAW_OPEN);

}

void left_low_green_high_green()
{
	setMotorTarget(scoopMotor, iScoopPos[1], 100);
	setMotorTarget(clawMotor, CLAW_OPEN, 100);
	GoStraight(5 cm, -60 as speed);

	pickUpTrigger = 4; liftLevel = 3; clawTarget = CLAW_CLOSE;
	startTask( pick_up_cube );

	GoStraight(10 cm, -30 as speed);
	setMotorTarget(liftMotorL, iLiftLevel[liftLevel],100);
	setMotorTarget(liftMotorR, iLiftLevel[liftLevel],100);

	GoStraight(55 cm, -40 as speed);

	clawAction(CLAW_OPEN);

	GoStraight(10 cm, 30 as speed);

	setMotorTarget(clawMotor, CLAW_CLOSE,30);
	setMotorTarget(liftMotorL, iLiftLevel[0],100);
	setMotorTarget(liftMotorR, iLiftLevel[0],100);
	Turn(-90 degree, ON_SPOT_TURN);

	GoStraight(30 cm, -40 as speed);
	Turn(-140 degree, ON_SPOT_TURN);

	GoStraight(20 cm, -40 as speed);
	pickUpTrigger = 4; liftLevel = 4; clawTarget = CLAW_OPEN;
	startTask( pick_up_cube );
	GoStraight(60 cm, -40 as speed0);
	Turn(-230 degree, ON_SPOT_TURN as speed);

	GoStraight(23 cm, -40 as speed);

	clawAction(CLAW_CLOSE);

	setMotorTarget(liftMotorL,iLiftLevel[1],50);
	setMotorTarget(liftMotorR,iLiftLevel[1],50);
	GoStraight(15 cm, 100 as speed);
}

void two_red_two_blue_on_left()
{
	setMotorTarget(scoopMotor, iScoopPos[1], 100);
	setMotorTarget(clawMotor, CLAW_OPEN, 100);
	setMotorTarget(liftMotorL,iLiftLevel[1],100);
	setMotorTarget(liftMotorR,iLiftLevel[1],100);
	Turn(-35 degree, ON_SPOT_TURN);
	Turn(-80 degree, RIGHT_WHEEL_TURN);

	GoStraight(20 cm, 90 as speed);
	setMotorTarget(scoopMotor, iScoopPos[0]+170, 100);
	GoStraight(10 cm, -100 as speed);

	//waitUntil(getTouchLEDValue(LED)==1);

	Turn(-135 degree, ON_SPOT_TURN);
	GoStraight(45 cm, 90 as speed);

	//waitUntil(getTouchLEDValue(LED)==1);

	Turn(-15 degree, ON_SPOT_TURN);

	//waitUntil(getTouchLEDValue(LED)==1);
	GoStraight(5 cm, 100 as speed);
	GoStraight(33 cm, -100 as speed);
}

void two_red_right()
{
	setMotorTarget(scoopMotor, iScoopPos[3], 100);
	setMotorTarget(clawMotor, CLAW_OPEN, 100);
	setMotorTarget(liftMotorL,iLiftLevel[0],100);
	setMotorTarget(liftMotorR,iLiftLevel[0],100);
	GoStraight(20 cm, -90 as speed);

	Turn(85 cm, ON_SPOT_TURN as speed);

	//waitUntil(getTouchLEDValue(LED)==1);

	GoStraight(30 cm, 90 as speed);
	turnNumber++;
	setMotorTarget(scoopMotor, iScoopPos[1]+ENCODER_UNIT_PER_SCOOP_ROUND*turnNumber, 100);
	GoStraight(20 cm, -60 as speed);

	//waitUntil(getTouchLEDValue(LED)==1);

	Turn(45 degree, ON_SPOT_TURN);

	//waitUntil(getTouchLEDValue(LED)==1);

	GoStraight(20 cm, 90 as speed);

	scoreBalls();

	GoStraight(15 cm, -90 as speed);

	Turn(-55 degree, ON_SPOT_TURN);

	GoStraight(35 cm, -100 as speed);
	Turn(-10 degree, ON_SPOT_TURN);

	setMotorSpeed(leftMotor, -100);
	setMotorSpeed(rightMotor, -100);
	wait1Msec(800);

	setMotorSpeed(leftMotor, 100);
	setMotorSpeed(rightMotor, 100);
	wait1Msec(300);

	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);

}

task main()
{

	setMotorEncoderUnits( encoderCounts );

	// Define 0 point for claw, scooper, and lift.
	setMotorSpeed(liftMotorL, -100);
	setMotorSpeed(liftMotorR, -100);
	setMotorSpeed(clawMotor, -50);
	setMotorSpeed(scoopMotor, -60);
	wait1Msec(2000);
	setMotorSpeed(liftMotorL, 0);	resetMotorEncoder(liftMotorL);
	setMotorSpeed(liftMotorR, 0);	resetMotorEncoder(liftMotorR);
	setMotorSpeed(clawMotor, 0);	resetMotorEncoder(clawMotor);
	setMotorSpeed(scoopMotor, 0); resetMotorEncoder(scoopMotor);

	// Get claw, scooper, and lift ready for the game
	setMotorTarget(scoopMotor, iScoopPos[1], 100);
	setMotorTarget(clawMotor, CLAW_OPEN, 100);
	setMotorTarget(liftMotorL, iLiftLevel[1], 100);
	setMotorTarget(liftMotorR, iLiftLevel[1], 100);
	wait1Msec(1000);

	iCheckBattLevel(7.8, 8.0);

	setTouchLEDColor(LED,colorOrange);
	waitUntil(getTouchLEDValue(LED) == 1);

	// Get drive train ready for the game
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	setMotorBrakeMode(leftMotor, motorHold);
	setMotorBrakeMode(rightMotor, motorHold);

	// On the mark
	LEDBusiness( colorGreen, 0, 0, 0, 0 );
	clearTimer( T1 );
	right_low_green_two_blue();

	LEDBusiness( colorGreen, 0, 0, 0, 0 );
	left_low_green_high_green();

	LEDBusiness( colorGreen, 0, 0, 0, 0 );
	two_red_two_blue_on_left();

	LEDBusiness( colorGreen, 0, 0, 0, 0 );
	two_red_right();

}
