#pragma config(Sensor, port6,  LED,            sensorVexIQ_LED)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void iCheckBattLevel(float min, float closemin){
	float nBattLevel = 0;
	float BattLevel = 0;
	for(int i = 0; i<1000; i++){
		BattLevel = BattLevel+(nImmediateBatteryLevel/1000);
		wait1Msec(10);
	}
	nBattLevel = Battlevel/1000;
	displayCenteredBigTextLine(3, "%f", nBattLevel);
	if(nBattLevel<min){
		setTouchLEDRGB(LED,255, 0, 0);
		waitUntil(getTouchLEDValue(LED)==1);
		setTouchLEDColor(LED, colorNone);
		}else if(nBattLevel<=closemin){
		setTouchLEDRGB(LED,255, 125, 125);
		waitUntil(getTouchLEDValue(LED)==1);
		setTouchLEDColor(LED, colorNone);
	}
}
task main()
{
	iCheckBattLevel(7.8, 8.0);


}
