#pragma config(Sensor, port1,  LED,            sensorVexIQ_LED)
#pragma config(Motor,  motor2,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor5,          liftMotorR,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          clawMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor8,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         liftMotorL,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         scoopMotor,    tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define CLAW_CLOSE 450
#define CLAW_OPEN 50
#define CLAW_DELTA 20
#define SCOOPER_DELTA 35
#define LIFT_DELTA 25
#define MS_PER_ENCODER_UNIT 1
#define ENCODER_UNIT_PER_SCOOP_ROUND 1920
#define WAIT_CYCLE 20
#define COUNT_PER_ROUND 960
#define MS_PER_DEGREE_ROBOT_TURN 12

int pickUpTrigger, clawTarget, liftLevel;
float timeStamp;

#define LIFT_LEVELS 5
int iLiftLevel[LIFT_LEVELS] = {15 ,420, 1100, 1500, 1830}; //pickup_inside, pickup_outside/transport,low_inside,low_outside,,high_inside

int iScoopPos[4] = { -300, 280, 815, 1000 }; //pick_cube, keep_ball/release cube, ready_to_scoop_ball, score_ball

int turnNumber = 0;

void iCheckBattLevel(float min, float closemin){
	float nBattLevel = 0;
	float BattLevel = 0;
	for(int i = 0; i<1000; i++){
		BattLevel = BattLevel+(nImmediateBatteryLevel/1000);
		wait1Msec(10);
	}
	nBattLevel = BattLevel/1000;
	displayCenteredBigTextLine(3, "%f", nBattLevel);
	if(nBattLevel<min){
		setTouchLEDRGB(LED,255, 0, 0);
		waitUntil(getTouchLEDValue(LED)==1);
		setTouchLEDColor(LED, colorNone);
		}else if(nBattLevel<=closemin){
		setTouchLEDRGB(LED,255, 125, 125);
		waitUntil(getTouchLEDValue(LED)==1);
		setTouchLEDColor(LED, colorNone);
	}
}

void LEDBusiness(int colour, int blinkTimeOn, int blinkTimeOff, int blinkColour, int blink)
{

	timeStamp = time1[T1];
	displayCenteredBigTextLine( 3, "%f", timeStamp );

	if (blink == 0)
	{
		setTouchLEDColor(LED, colour);
		waitUntil( getTouchLEDValue(LED) == 1 );
	}
	else if (blink ==1)
	{
		setTouchLEDColor(LED,colour);
		waitUntil(getTouchLEDValue(LED) == 1);
		setTouchLEDColor(LED,blinkColour);
		setTouchLEDBlinkTime(LED, blinkTimeOn, blinkTimeOff);
	}

}

void clawAction(int targetName)
{
	setMotorTarget( clawMotor, targetName, 100 );
	wait1Msec( abs( CLAW_CLOSE - CLAW_OPEN ) * MS_PER_ENCODER_UNIT );
	setMotorSpeed( clawMotor, 0 );
}

void scoreBalls()
{
	setMotorSpeed(leftMotor,30);
	setMotorSpeed(rightMotor,30);

	setMotorTarget(scoopMotor,turnNumber*ENCODER_UNIT_PER_SCOOP_ROUND+iScoopPos[3],100);
	wait1Msec( abs( iScoopPos[3] - iScoopPos[1] ) * MS_PER_ENCODER_UNIT );
	wait1Msec(100);
	setMotorSpeed(leftMotor,0);
	setMotorSpeed(rightMotor,0);
	setMotorTarget(scoopMotor,turnNumber*ENCODER_UNIT_PER_SCOOP_ROUND+iScoopPos[2],100);
	wait1Msec( abs( iScoopPos[3] - iScoopPos[2] ) * MS_PER_ENCODER_UNIT );
}

task pick_up_cube()
{
	clearTimer(T2);

	while ( time1[T2] < pickUpTrigger )
	{
		wait1Msec( WAIT_CYCLE );
	}

	clawAction( clawTarget );
	setMotorTarget( liftMotorL, iLiftLevel[liftLevel], 100 );
	setMotorTarget( liftMotorR, iLiftLevel[liftLevel], 100 );
	wait1Msec(abs(getMotorEncoder(liftMotorL)-iLiftLevel[liftLevel])*MS_PER_ENCODER_UNIT);
	wait1Msec(300);
	EndTimeSlice();
}


void moveRobot(int waitTime, int leftSpeed, int rightSpeed)
{
	setMotorSpeed(leftMotor, leftSpeed);
	setMotorSpeed(rightMotor, rightSpeed);
	wait1Msec(waitTime);
}

void right_low_green_two_blue()
{
	//goStraight(5, -60);

	pickUpTrigger = 4; liftLevel = 3; clawTarget = CLAW_CLOSE;
	startTask( pick_up_cube );

	//goStraight(10, -30);
	setMotorTarget(liftMotorL, iLiftLevel[liftLevel],100);
	setMotorTarget(liftMotorR, iLiftLevel[liftLevel],100);

	//goStraight(55, -40);

	clawAction(CLAW_OPEN);

	//goStraight(5, 30);
	setMotorTarget(clawMotor, CLAW_CLOSE,30);
	setMotorTarget(liftMotorL, iLiftLevel[1],100);
	setMotorTarget(liftMotorR, iLiftLevel[1],100);
	//Turn(110, ON_SPOT_TURN);

	//goStraight(25, 60);
	setMotorTarget(scoopMotor, iScoopPos[0], 100);
	//goStraight(10, -40);

	//Turn(185, ON_SPOT_TURN);

	//goStraight(65, -100);

	clawAction(CLAW_OPEN);

}

void left_low_green_high_green()
{
	setMotorTarget(scoopMotor, iScoopPos[1], 100);
	setMotorTarget(clawMotor, CLAW_OPEN, 100);
	//goStraight(5, -60);

	pickUpTrigger = 4; liftLevel = 3; clawTarget = CLAW_CLOSE;
	startTask( pick_up_cube );

	//goStraight(10, -30);
	setMotorTarget(liftMotorL, iLiftLevel[liftLevel],100);
	setMotorTarget(liftMotorR, iLiftLevel[liftLevel],100);

	//goStraight(55, -40);

	clawAction(CLAW_OPEN);

	//goStraight(10, 30);

	setMotorTarget(clawMotor, CLAW_CLOSE,30);
	setMotorTarget(liftMotorL, iLiftLevel[0],100);
	setMotorTarget(liftMotorR, iLiftLevel[0],100);
	//Turn(-90, ON_SPOT_TURN);

	//goStraight(30, -40);
	//Turn(-140, ON_SPOT_TURN);

	//goStraight(20, -40);
	pickUpTrigger = 4; liftLevel = 4; clawTarget = CLAW_OPEN;
	startTask( pick_up_cube );
	//goStraight(60, -400);
	//Turn(-230, ON_SPOT_TURN);

	//goStraight(23, -40);

	clawAction(CLAW_CLOSE);

	setMotorTarget(liftMotorL,iLiftLevel[1],50);
	setMotorTarget(liftMotorR,iLiftLevel[1],50);
	//goStraight(15, 100);
}

void two_red_two_blue_on_left()
{
	setMotorTarget(scoopMotor, iScoopPos[1], 100);
	setMotorTarget(clawMotor, CLAW_OPEN, 100);
	setMotorTarget(liftMotorL,iLiftLevel[1],100);
	setMotorTarget(liftMotorR,iLiftLevel[1],100);
	//Turn(-35, ON_SPOT_TURN);
	//Turn(-80, RIGHT_WHEEL_TURN);

	//goStraight(20, 90);
	setMotorTarget(scoopMotor, iScoopPos[0]+170, 100);
	//goStraight(10, -100);

	//waitUntil(getTouchLEDValue(LED)==1);

	//Turn(-135, ON_SPOT_TURN);
	//goStraight(45, 90);

	//waitUntil(getTouchLEDValue(LED)==1);

	//Turn(-15, ON_SPOT_TURN);

	//waitUntil(getTouchLEDValue(LED)==1);
	//goStraight(5, 100);
	//goStraight(33, -100);
}

void two_red_right()
{
	setMotorTarget(scoopMotor, iScoopPos[3], 100);
	setMotorTarget(clawMotor, CLAW_OPEN, 100);
	setMotorTarget(liftMotorL,iLiftLevel[0],100);
	setMotorTarget(liftMotorR,iLiftLevel[0],100);
	//goStraight(20, -90);

	//Turn(85, ON_SPOT_TURN);

	//waitUntil(getTouchLEDValue(LED)==1);

	//goStraight(30, 90);
	turnNumber++;
	setMotorTarget(scoopMotor, iScoopPos[1]+ENCODER_UNIT_PER_SCOOP_ROUND*turnNumber, 100);
	//goStraight(20, -60);

	//waitUntil(getTouchLEDValue(LED)==1);

	//Turn(45, ON_SPOT_TURN);

	//waitUntil(getTouchLEDValue(LED)==1);

	//goStraight(20, 90);

	scoreBalls();

	//goStraight(15, -90);

	//Turn(-55, ON_SPOT_TURN);

	//goStraight(35, -100);
	//Turn(-10, ON_SPOT_TURN);

	setMotorSpeed(leftMotor, -100);
	setMotorSpeed(rightMotor, -100);
	wait1Msec(800);

	setMotorSpeed(leftMotor, 100);
	setMotorSpeed(rightMotor, 100);
	wait1Msec(300);

	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);

}

task main()
{

	setMotorEncoderUnits( encoderCounts );

	// Define 0 point for claw, scooper, and lift.
	setMotorSpeed(liftMotorL, -100);
	setMotorSpeed(liftMotorR, -100);
	setMotorSpeed(clawMotor, -50);
	setMotorSpeed(scoopMotor, -60);
	wait1Msec(2000);
	setMotorSpeed(liftMotorL, 0);	resetMotorEncoder(liftMotorL);
	setMotorSpeed(liftMotorR, 0);	resetMotorEncoder(liftMotorR);
	setMotorSpeed(clawMotor, 0);	resetMotorEncoder(clawMotor);
	setMotorSpeed(scoopMotor, 0); resetMotorEncoder(scoopMotor);

	// Get claw, scooper, and lift ready for the game
	setMotorTarget(scoopMotor, iScoopPos[1], 100);
	setMotorTarget(clawMotor, CLAW_OPEN, 100);
	setMotorTarget(liftMotorL, iLiftLevel[1], 100);
	setMotorTarget(liftMotorR, iLiftLevel[1], 100);
	wait1Msec(1000);

	iCheckBattLevel(7.8, 8.0);

	setTouchLEDColor(LED,colorOrange);
	waitUntil(getTouchLEDValue(LED) == 1);

	// Get drive train ready for the game
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	setMotorBrakeMode(leftMotor, motorHold);
	setMotorBrakeMode(rightMotor, motorHold);

	// On the mark
	LEDBusiness( colorGreen, 0, 0, 0, 0 );
	clearTimer( T1 );
	right_low_green_two_blue();

	LEDBusiness( colorGreen, 0, 0, 0, 0 );
	left_low_green_high_green();

	LEDBusiness( colorGreen, 0, 0, 0, 0 );
	two_red_two_blue_on_left();

	LEDBusiness( colorGreen, 0, 0, 0, 0 );
	two_red_right();

}
