#pragma config(Sensor, port11, gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,          rightMotor,    tmotorVexIQ, openLoop, driveRight, encoder)
#pragma config(Motor,  motor6,          leftMotor,     tmotorVexIQ, openLoop, reversed, driveLeft, encoder)
#pragma config(Motor,  motor10,         armMotor,      tmotorVexIQ, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void GoStraight(int motorSpeed, float direction, float )
{
task main()
{
	while (true)
	{

	}
}
