#pragma config(Sensor, port4,  Gyro,           sensorVexIQ_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
static GyroNull(){
	int Drift = 0;
	float DriftPerSecond = 0.0;
	resetGyro(Gyro);
	clearTimer(T1);
	while(true){
		if(timer1=600000){
			Drift = getGyroDegrees(Gyro);
			break;
		}
	}
	DriftPerSecond = Drift/60.0;
	return(DriftPerSecond);
}
task main()
{
	resetGyro(Gyro);
	clearTimer(T1);

	while(true)
	{
		writeDebugStream("%f: Gyro: %f\n",time1[T1]/1000, getGyroDegreesFloat(Gyro));
		sleep(1000);
	}
}
