#pragma config(Sensor, port4,  Gyro,           sensorVexIQ_Gyro)
<<<<<<< HEAD
#pragma config(Sensor, port8,  LED,            sensorVexIQ_LED)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define GYRO_SAMPLEING_SECONDS 10

float fGyroDriftRate = 0;

void setGyroStable()
{
	setTouchLEDColor(LED,colorRed);
	setTouchLEDBlinkTime(LED, 14,6);

	wait(3);
	setTouchLEDBlinkTime(LED, 0,1);
	wait(2);

	setTouchLEDColor(LED,colorGreen);
	setTouchLEDBlinkTime(LED, 8, 12);

	resetGyro(Gyro);
	clearTimer(T4);
	wait(GYRO_SAMPLEING_SECONDS);
	setTouchLEDBlinkTime(LED, 4, 4);
	wait(1);
	setTouchLEDColor(LED,colorNone);
	setTouchLEDBlinkTime(LED, 1, 0);

	fGyroDriftRate = getGyroDegreesFloat(Gyro) / GYRO_SAMPLEING_SECONDS;
}

float getGyroStable()
{
	return getGyroDegreesFloat(Gyro) - fGyroDriftRate * time1[T4] / 1000;
}

=======
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
static GyroNull(){
	int Drift = 0;
	float DriftPerSecond = 0.0;
	resetGyro(Gyro);
	clearTimer(T1);
	while(true){
		if(timer1=600000){
			Drift = getGyroDegrees(Gyro);
			break;
		}
	}
	DriftPerSecond = Drift/60.0;
	return(DriftPerSecond);
}
>>>>>>> cd58a9a434a7d0e6ac075fd3ca35cb6aa89068a9
task main()
{
	clearTimer(T4);
	writeDebugStream("%f: Gyro and Timer Resetted\n", time1[T4]/1000);
	writeDebugStream("%f: Sampling Time = %d Seconds\n", time1[T4]/1000, GYRO_SAMPLEING_SECONDS);

	setGyroStable();
	writeDebugStream("%f: Sampled Drifting Rate = %f\n", time1[T4]/1000, fGyroDriftRate);

	resetGyro(Gyro);
	clearTimer(T4);

	while(true)
	{
		displayCenteredBigTextLine( 3, "%d, %d", getGyroStable(), getGyroDegrees(Gyro) );
		//writeDebugStream("%f:  RawGyro: %f, 839Gyro: %f\n",time1[T4]/1000, getGyroDegreesFloat(Gyro), gyroStablized());
		//sleep(1000);
	}
}
