#pragma config(Sensor, port6,  gyro,           sensorVexIQ_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float integral = 0;
float dt = 250;
float prev_error = 0;
float allowed_time = 7.5;
float setpoint = 0
void turn(int speed)
{
	setMotorSpeed();
}
void PIDControl (float Kp, float Ki, float Kd, float delta)
{
	while (true)
	{
		float measured_value = getGyroHeadingFloat(gyro);
		int error = setpoint - measured_value;
		integral = integral + error * dt;
		float derivative = ( error - prev_error ) / dt;
		float output = Kp * error + Ki * integral + Kd * derivative;
		turn(output);
		prev_error = error;
		if ( error <= delta || time1[T1] > allowed_time )
		{
			break;
		}
		wait1Msec ( dt );
	}

}

task main()
{
	PIDControl(0.01, 0.01, 0.01, 0.01, 0.01)
}
