#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor7,          clawMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         tailMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         armMotor,      tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define GEAR_RATIO 1.5f
#define ARM_SPEED 100
#define TAIL_SPEED 60
#define CLAW_SPEED 100

#define CLAW_OPEN -10
#define CLAW_CLOSE -170
#define CLAW_DELTA 25

#define TAIL_UP 150
#define TAIL_DOWN 10
#define TAIL_DELTA 25

int iChA_filtered=0, iChC_filtered=0;


int iDriveMapping[101] = {
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
10,10,10,10,10,10,10,10,10,10,
10,10,10,10,10,10,10,10,10,10,
20,20,20,20,20,20,20,20,20,20,
30,30,30,30,30,30,30,30,30,30,
40,40,40,40,40,40,40,40,40,40,
50,50,50,50,50,50,50,50,50,50,
60,62,64,66,68,70,72,74,76,78,
84,88,92,96,100,100,100,100,100,100,100};


int iTurnMapping[101] = {
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
30,30,30,30,30,30,30,30,30,30,
30,30,30,30,30,31,32,33,34,36,
38,40,40,40,40,40,40,42,46,48,
50,50,50,50,50,50,50,52,54,56,
58,58,59,59,60,60,60,60,60,60,
60,60,60,60,60,60,60,60,60,60,
60,60,60,62,62,63,63,63,63,63,
64,64,64,64,64,64,64,64,64,64,64};


task main()
{
	setMotorSpeed(clawMotor,100);
	setMotorSpeed(tailMotor,-100);
	wait(2);
	resetMotorEncoder(clawMotor);
	resetMotorEncoder(tailMotor);

	repeat (forever)
	{

		iChA_filtered=iDriveMapping[abs(getJoystickValue(ChA))]*sgn(getJoystickValue(ChA));
		iChC_filtered=iTurnMapping[abs(getJoystickValue(ChC))]*sgn(getJoystickValue(ChC));
		//iChC_filtered=iDriveMapping[abs(getJoystickValue(ChC))]*sgn(getJoystickValue(ChC))/GEAR_RATIO

		setMotorSpeed(leftMotor,(iChA_filtered+iChC_filtered)/1);
		setMotorSpeed(rightMotor,(iChA_filtered-iChC_filtered)/1);



		if (getJoystickValue(BtnLDown)==1)
		{
			if ( abs(getMotorEncoder(tailMotor) - TAIL_DOWN) < TAIL_DELTA )
			{
				setMotorTarget(tailMotor,TAIL_UP,100);
				wait1Msec(500);
			}
			else
			{
				setMotorTarget(tailMotor,TAIL_DOWN,100);
				wait1Msec(500);
			}
		}


    if (getJoystickValue(BtnRUp)== 1)
		{
			setMotorSpeed(armMotor, -1*ARM_SPEED);
		}
		else if (getJoystickValue(BtnRDown)==1)
		{
			setMotorSpeed(armMotor, ARM_SPEED);
		}
		else
		{
			setMotorSpeed(armMotor, 0);
		}

		if (getJoystickValue(BtnLUp)==1)
		{
			if ( abs(getMotorEncoder(clawMotor) - CLAW_OPEN) < CLAW_DELTA )
			{
				setMotorTarget(clawMotor,CLAW_CLOSE,100);
				wait1Msec(500);
			}
			else
			{
				setMotorTarget(clawMotor,CLAW_OPEN,100);
				wait1Msec(500);
			}
		}
	}
}
