#pragma config(Sensor, port2,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void straightDistance(float kp, int power, int heading, int distance)
{
	int circumference = 197.82;
	int targetEncoderValue;
	targetEncoderValue = distance/circumference*360;
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	while(getMotorEncoder(leftMotor) < targetEncoderValue)
	{

		int error;
		getMotorEncoder(leftMotor);
		error = heading - getGyroDegrees(gyroSensor);
		int output = error*kp;
		setMotorSpeed(leftMotor, power + output);
		setMotorSpeed(rightMotor, power - output);
		wait(20);
	}

}

task main()
{
	setMotorBrakeMode(leftMotor, motorBrake);
	setMotorBrakeMode(rightMotor, motorBrake);
	straightDistance(0.5, 10, 0, 10);

}
