#pragma config(Motor,  motor7,          intakeMotor,   tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor8,          catapultMotor, tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor9,          FL,            tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor10,         FR,            tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         BL,            tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor12,         BR,            tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float iChA_filtered = 0.0;
float iChC_filtered = 0.0;
int iDriveMapping[101] = {
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
10,10,10,10,10,10,10,10,10,10,
10,10,10,10,10,10,10,10,10,10,
20,20,20,20,20,20,20,20,20,20,
30,30,30,30,30,30,30,30,30,30,
40,40,40,40,40,40,40,40,40,40,
50,50,50,50,50,50,50,50,50,50,
60,62,64,66,68,70,72,74,76,78,
84,88,92,96,100,100,100,100,100,100,100};

int iTurnMapping[101] = {
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
10,10,10,10,10,10,10,10,10,10,
10,10,10,10,10,10,10,10,10,10,
20,20,20,20,20,20,20,20,20,20,
30,30,30,30,30,30,30,30,30,30,
40,40,40,40,40,40,40,40,40,40,
50,50,50,50,50,50,50,50,50,50,
60,62,64,66,68,70,72,74,76,78,
84,88,92,96,100,100,100,100,100,100,100};

task intake
{
	while(true)
	{
		if(getJoystickValue(BtnLUp) == 1)
		{
			setMotorSpeed(intakeMotor, 100)
			wait1Msec(200)
			waitUntil(getJoystickValue(BtnLUp) == 1)
			if(getJoystickValue(BtnLUp) == 1)
			{
				setMotorSpeed(intakeMotor, 0)
			}
		}
	}
}
task main()
{
	startTask(intake)
	while(true)
	{
		iChA_filtered=iDriveMapping[abs(getJoystickValue(ChA))]*sgn(getJoystickValue(ChA));
		iChC_filtered=iTurnMapping[abs(getJoystickValue(ChC))]*sgn(getJoystickValue(ChC));
		setMotorSpeed(BL,(iChA_filtered+iChC_filtered));
		setMotorSpeed(FL,(iChA_filtered+iChC_filtered));
		setMotorSpeed(FR,(iChA_filtered-iChC_filtered));
		setMotorSpeed(BR,(iChA_filtered-iChC_filtered));
		if(getJoystickValue(BtnRUp) == 1)
		{
			setMotorSpeed(catapultMotor, 100);
		}
		else
		{
			setMotorSpeed(catapultMotor, 0)
		}
	}
}
