#pragma config(Sensor, port4,  Gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port8,  LED,            sensorVexIQ_LED)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor7,          clawMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         tailMotor,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor12,         armMotor,      tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define WAIT_CYCLE 20

void turnDecel(int targetHeading, float Ki, float Kp, int baseSpeed, int delta)
{
	float error = 0, integral = 0, output;


	while ( abs( getGyroDegreesFloat(Gyro) - targetHeading ) > delta )
	{
		error = getGyroDegreesFloat(Gyro) - targetHeading;
		integral = integral + error;
		output = error * Kp + integral * Ki;

		setMotorSpeed(leftMotor, sgn(error) * baseSpeed + output);
		setMotorSpeed(rightMotor, -sgn(error) * baseSpeed - output);

		//writeDebugStreamLine("%d:  %d,  %d,  %d", time1[T1], error, integral, output);
		wait1Msec(WAIT_CYCLE);
	}
		setMotorSpeed(leftMotor, 0);
		setMotorSpeed(rightMotor, 0);
}
task main()
{

	wait(1);
	clearTimer(T1);
	resetGyro(Gyro);
	setMotorEncoderUnits(encoderCounts);
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	setMotorBrakeMode(leftMotor, motorHold);
	setMotorBrakeMode(rightMotor, motorHold);

	turnDecel( 90, 0, 0.6, 5, 2 );

	wait(1);

	turnDecel( -90, 0, 0.6, 5, 2 );

}
