#pragma config(Sensor, port10, LED,            sensorVexIQ_LED)
#pragma config(Sensor, port12, gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,          BR,            tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          liftMotorL,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor5,          BL,            tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          FL,            tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          FR,            tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         liftMotorR,    tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float setpoint = 0;
float integral = 0;
float dt = 250;
float prev_error = 0;
float allowed_time = 7.5;
int artificial_ChC_Reading = 0;


int iDriveMapping[101] = {
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
10,10,10,10,10,10,10,10,10,10,
10,10,10,10,10,10,10,10,10,10,
20,20,20,20,20,20,20,20,20,20,
30,30,30,30,30,30,30,30,30,30,
40,40,40,40,40,40,40,40,40,40,
50,50,50,50,50,50,50,50,50,50,
60,62,64,66,68,70,72,74,76,78,
84,88,92,96,100,100,100,100,100,100,100};

int iStrafeMapping[101] = {
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
10,10,10,10,10,10,10,10,10,10,
10,10,10,10,10,10,10,10,10,10,
20,20,20,20,20,20,20,20,20,20,
25,25,25,25,25,25,25,25,25,25,
40,40,40,40,40,40,40,40,40,40,
60,60,60,60,60,60,60,60,60,60,
80,80,80,80,80,80,80,80,80,80,
100,100,100,100,100,100,100,100,100,100,100};

int iTurnMapping[101] = {
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
30,30,30,30,30,30,30,30,30,30,
30,30,30,30,30,31,32,33,34,36,
38,40,40,40,40,40,40,42,46,48,
50,50,50,50,50,50,50,52,54,56,
58,58,59,59,60,60,60,60,60,60,
60,60,60,60,60,60,60,60,60,60,
60,60,60,62,62,63,63,64,64,64,
66,66,66,66,66,100,100,100,100,100,100};



task flashLED()
{
	while( true )
	{
		setTouchLEDRGB(LED, 0, 255, 0);
		sleep( 500 );
		setTouchLEDRGB(LED, 0, 255, 255);
		sleep( 500 );
	}
}




task main()
{
	int iChC_filtered;
	int iChA_filtered;
	int iChB_filtered;
	setMotorBrakeMode(FL, motorHold);
	setMotorBrakeMode(FR, motorHold);
	setMotorBrakeMode(BR, motorHold);
	setMotorBrakeMode(BL, motorHold);
	startTask( flashLED );
	while(true)
	{
//		setpoint = 0; //later, we will plug in ChC reading.
//		PIDControl(setpoint, 0.5, 0, 0.1, 0.1);


		iChA_filtered = iDriveMapping[abs(getJoystickValue(ChA))]*sgn(getJoystickValue(ChA));
		iChB_filtered = iStrafeMapping[abs(getJoystickValue(ChB))]*sgn(getJoystickValue(ChB));
		if ( abs(getJoystickValue(ChC)) <= 15 )
		{
			iChC_filtered = iTurnMapping[abs(getJoystickValue(ChC))]*sgn(getJoystickValue(ChC));
		}
		else
		{
			iChC_filtered = iTurnMapping[abs(getJoystickValue(ChC))]*sgn(getJoystickValue(ChC));
		}


		if (getJoystickValue(BtnRUp) == 1)
		{
			setMotorSpeed(liftMotorL, 100);
			setMotorSpeed(liftMotorR, 100);
		}
		else if ( getJoystickValue(BtnRDown) == 1 )
		{
			setMotorSpeed(liftMotorL, -100);
			setMotorSpeed(liftMotorR, -100);
		}
		else
		{
			setMotorSpeed(liftMotorL, 0);
			setMotorSpeed(liftMotorR, 0);
		}
		setMotorSpeed(BL, 0 + iChA_filtered - iChB_filtered - iChC_filtered );
		setMotorSpeed(BR, 0 - iChA_filtered - iChB_filtered - iChC_filtered );
		setMotorSpeed(FL, 0 + iChA_filtered + iChB_filtered - iChC_filtered );
		setMotorSpeed(FR, 0 - iChA_filtered + iChB_filtered - iChC_filtered );
		wait1Msec(20);
	}
}
