#pragma config(Sensor, port10, LED,            sensorVexIQ_LED)
#pragma config(Sensor, port12, gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,          BR,            tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          clawMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          BL,            tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          FL,            tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          FR,            tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         liftMotor,     tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int error;
float integral = 0;
float dt = 25;
float prev_error = 0;
float allowed_time = 7.5;
float output;
float delta = 10;
int artificial_ChC_Reading = 0;
float desired_heading;
bool claw_working = false;
bool claw_to_close = false;
#define ARM_DELTA 10
#define CLAW_DELTA 15
#define MS_PER_ENCODER_UNIT 3

#define LIFT_LEVELS 2
int iLiftLevel[LIFT_LEVELS] = {30, 450};
int in_between_level = 405

#define CLAW_CLOSED 15
#define CLAW_OPEN 145

/*
int iDriveMapping[101] = {
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
10,10,10,10,10,10,10,10,10,10,
10,10,10,10,10,10,10,10,10,10,
20,20,20,20,20,20,20,20,20,20,
30,30,30,30,30,30,30,30,30,30,
40,40,40,40,40,40,40,40,40,40,
50,50,50,50,50,50,50,50,50,50,
60,62,64,66,68,70,72,74,76,78,
84,88,92,96,100,100,100,100,100,100,100};

int iStrafeMapping[101] = {
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
10,10,10,10,10,10,10,10,10,10,
10,10,10,10,10,10,10,10,10,10,
20,20,20,20,20,20,20,20,20,20,
25,25,25,25,25,25,25,25,25,25,
30,30,30,30,30,30,30,40,40,40,
50,50,50,50,50,60,60,60,60,60,
80,80,80,80,80,80,80,80,80,80,
100,100,100,100,100,100,100,100,100,100,100};
*/
int iDriveMapping[101] = {
	0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,
	10,10,10,10,10,10,10,10,10,10,
	10,10,10,10,10,10,10,10,10,10,
	20,20,20,20,20,20,20,20,20,20,
	20,20,20,20,20,20,20,20,20,20,
	30,30,30,30,30,30,30,30,30,30,
	30,30,30,30,30,30,30,30,30,30,
	30,30,30,30,30,30,30,30,30,30,
	40,40,40,60,60,80,80,100,100,100,100};

int iStrafeMapping[101] = {
	0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,
	10,10,10,10,10,10,10,10,10,10,
	10,10,10,10,10,10,10,10,10,10,
	20,20,20,20,20,20,20,20,20,20,
	20,20,20,20,20,20,20,20,20,20,
	30,30,30,30,30,30,30,30,30,30,
	30,30,30,30,30,30,30,30,30,30,
	30,30,30,30,30,30,30,30,30,30,
	40,40,40,60,60,80,80,100,100,100,100};

int iTurnMapping[101] = {
	0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,
	10,10,10,10,10,10,10,10,10,10,
	10,10,10,10,10,10,10,10,10,10,
	20,20,20,20,20,20,20,20,20,20,
	20,20,20,20,20,20,20,20,20,20,
	30,30,30,30,30,30,30,30,30,30,
	30,30,30,30,30,30,30,30,30,30,
	30,30,30,30,30,30,30,30,30,30,
	40,40,40,40,40,40,40,60,60,60,60};

task main()
{
	int iChC_filtered;
	int iChA_filtered;
	int iChB_filtered;

	setMotorBrakeMode(FL, motorHold);
	setMotorBrakeMode(FR, motorHold);
	setMotorBrakeMode(BR, motorHold);
	setMotorBrakeMode(BL, motorHold);
	setMotorBrakeMode(clawMotor, motorCoast);
	setMotorBrakeMode( liftMotor, motorHold );

	setMotorSpeed(clawMotor, -50);
	setMotorSpeed(liftMotor, -30);
	wait1Msec(3000);

	resetMotorEncoder(clawMotor);
	resetMotorEncoder(liftMotor);

	setMotorSpeed(clawMotor, 0);
	setMotorSpeed(liftMotor, 0);

	claw_to_close = true;
	setMotorTarget(clawMotor, CLAW_CLOSED, 60);
	setMotorTarget(liftMotor, iLiftLevel[0], 100);
	wait1Msec(1000);
	setMotorSpeed(clawMotor, 0);

	resetGyro(gyro);
	desired_heading = 0;

	//startTask( flashLED );


	int claw_position, prev_claw = 0;

	while (true)
	{
		if (getJoystickValue(BtnLUp)==1 && claw_working == false)
		{
			if (claw_to_close)
			{
				claw_to_close = false
			}
			else
			{
				claw_to_close = true
			}
			claw_working = true
		}

		if (claw_working)
		{
			if (claw_to_close)
			{
				setMotorBrakeMode(clawMotor, motorCoast);
				setMotorTarget(clawMotor,CLAW_CLOSED,100);
				wait1Msec( abs( CLAW_CLOSED - CLAW_OPEN ) * MS_PER_ENCODER_UNIT );
				setMotorSpeed(clawMotor, 0);
				if ( abs(getMotorEncoder(liftMotor) - iLiftLevel[1]) < ARM_DELTA  )
				{
					setMotorTarget(liftMotor, in_between_level, 100);
					setMotorSpeed(BL, -50 );
					setMotorSpeed(BR, 50 );
					setMotorSpeed(FL, -50 );
					setMotorSpeed(FR, 50 );
					wait1Msec(500);
					setMotorSpeed(BL, 0 );
					setMotorSpeed(BR, 0 );
					setMotorSpeed(FL, 0 );
					setMotorSpeed(FR, 0 );
				}
				claw_working = false
			}
			else
			{
				setMotorBrakeMode(clawMotor, motorHold);
				claw_position = getMotorEncoder(clawMotor);
				if (prev_claw == claw_position)
				{
					setMotorSpeed(clawMotor, 0);
					claw_working = false;
					prev_claw = 0;
				}
				else
				{
					setMotorSpeed(clawMotor, 100);
					wait1Msec(100);
				}
				prev_claw = claw_position;
			}
		}
		wait1Msec(dt);
	}
}
